#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys
import torch
from diffusers import AutoencoderKL, StableDiffusionInpaintPipeline
from huggingface_hub import hf_hub_download

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import MODEL_FILENAME, VAE_FILENAME, CACHE

# Make cache folders
if not os.path.exists(CACHE):
    os.makedirs(CACHE)

realisticVision_path = hf_hub_download(repo_id="SG161222/Realistic_Vision_V5.1_noVAE", filename=MODEL_FILENAME, local_dir=CACHE)
vae_path = hf_hub_download(repo_id="stabilityai/sd-vae-ft-mse-original", filename=VAE_FILENAME, local_dir=CACHE)